name: main

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: "1.25"
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v2.4
      - uses: actions/setup-go@v3
        with:
          go-version: "1.25"
      - name: make ci
        run: make ci
