name: main

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: "1.20"
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.51
      - uses: actions/setup-go@v3
        with:
          go-version: "1.20"
      - name: make lint
        run: make lint
      - name: make test
        run: make test
